---
- name: Konfiguration fuer windows host
  hosts: all
  vars:
    # ansible_user: user      # Set your username for windows here
    # ansible_password: user  # Set your password for windows here
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:

    - name: Install kicad
      win_chocolatey:
        name: kicad
        state: present

    - name: Install vscode
      win_chocolatey:
        name: vscode
        state: present

    - name: Install git
      win_chocolatey:
        name: git
        state: present

    - name: Install inkscape
      win_chocolatey:
        name: inkscape
        state: present

    - name: Install freecad
      win_chocolatey:
        name: freecad
        state: present

    - name: Install googlechrome
      win_chocolatey:
        name: googlechrome
        state: latest

    - name: Install autodesk-fusion360
      win_chocolatey:
        name: autodesk-fusion360
        state: present

    - name: Install docker-desktop
      win_chocolatey:
        name: docker-desktop
        state: latest
    
    - name: Install docker-compose
      win_chocolatey:
        name: docker-compose
        state: latest

    - name: Install synctrayzor
      win_chocolatey:
        name: synctrayzor
        state: latest

    - name: Install 7zip
      win_chocolatey:
        name: 7zip
        state: latest

    - name: Install vlc
      win_chocolatey:
        name: vlc
        state: latest

    - name: Install putty
      win_chocolatey:
        name: putty
        state: latest

    - name: Install skype
      win_chocolatey:
        name: skype
        state: latest

    - name: Install teamviewer
      win_chocolatey:
        name: teamviewer
        state: latest

    - name: Install nodejs
      win_chocolatey:
        name: nodejs
        state: latest

    - name: Install calibre
      win_chocolatey:
        name: calibre
        state: latest

    - name: Install spotify
      win_chocolatey:
        name: spotify
        state: latest

    - name: Install pdf24
      win_chocolatey:
        name: pdf24
        state: latest

    - name: Install jetbrainstoolbox
      win_chocolatey:
        name: jetbrainstoolbox
        state: latest
        

############################################################################
## Change Registry 

    - name: Show Hidden Files in Explorer
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: Hidden
        data: 1

    - name: Show Hidden System Files in Explorer
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: ShowSuperHidden
        data: 1

    - name: Show File Extension in Explorer
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        data: 0
        
##TODO: Extend Registry Entryies for Taskbar
############################################################################
## Add Git Repos

    - name: Create directory structure
      win_file:
        path: "C:\\Users\\{{ansible_user}}\\Projects"
        state: directory

    - name: win-git clone adolfs-frontend (For this to work, a git clone must be made once on the windows machine [confirm ssh key])
      win_git:
        repo: "git@github.com:piapiekarek/adolfs-frontend.git"
        dest: "C:\\Users\\{{ansible_user}}\\Projects\\adolfs-frontend"
        branch: master
        update: no
        accept_hostkey: yes

    - name: win-git clone lab-ansible-cad-workstation-configuration
      win_git:
        repo: "git@github.com:RT-CUSTOMZ/lab-ansible-cad-workstation-configuration.git"
        dest: "C:\\Users\\{{ansible_user}}\\Projects\\lab-ansible-cad-workstation-configuration"
        branch: master
        update: no
        accept_hostkey: yes

    - name: win-git clone PI-Setup-Kioskmode
      win_git:
        repo: "git@github.com:RT-CUSTOMZ/PI-Setup-Kioskmode.git"
        dest: "C:\\Users\\{{ansible_user}}\\Projects\\pi-setup-kioskmode"
        branch: master
        update: no
        accept_hostkey: yes
    - name: win-git clone RT-CUSTOMZ.github.io.git
      win_git:
        repo: "git@github.com:RT-CUSTOMZ/RT-CUSTOMZ.github.io.git"
        dest: "C:\\Users\\{{ansible_user}}\\Projects\\rt-customz.github.io"
        branch: master
        update: no
        accept_hostkey: yes
    
    - name: win-git clone CoffeeScale-HW
      win_git:
        repo: "git@github.com:RT-CUSTOMZ/CoffeeScale-HW.git"
        dest: "C:\\Users\\{{ansible_user}}\\Projects\\coffeeScale-HW"
        branch: master
        update: no
        accept_hostkey: yes




####################### Add Kicad plugins #######################
    - name: Create directory structure for Kicad
      win_file:
        path: "%APPDATA%\\kicad\\scripting\\plugins"
        state: directory

    - name: win-git clone kicad_rt_export script
      win_git:
        repo: "git@github.com:RT-CUSTOMZ/kicad_rt_export.git"
        dest: "AppData\\Roaming\\kicad\\scripting\\plugins\\kicad_rt_export"
        branch: master
        update: yes
        accept_hostkey: yes

    - name: win-git clone InteractiveHtmlBom
      win_git:
        repo: "git@github.com:openscopeproject/InteractiveHtmlBom.git"
        dest: "AppData\\Roaming\\kicad\\scripting\\plugins\\InteractiveHtmlBom"
        branch: master
        update: yes
        accept_hostkey: yes

