---
- name: Konfiguration fuer windows rtlab host
  hosts: all
  vars:
    ansible_user: user
    ansible_password: user
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:

    - name: Install kicad
      win_chocolatey:
        name: kicad
        state: present

    - name: Install vscode
      win_chocolatey:
        name: vscode
        state: present

    - name: Install arduino
      win_chocolatey:
        name: arduino
        state: present

    - name: Install git
      win_chocolatey:
        name: git
        state: present

    - name: Install inkscape
      win_chocolatey:
        name: inkscape
        state: present

    - name: Install freecad
      win_chocolatey:
        name: freecad
        state: present

    - name: Install autodesk-fusion360
      win_chocolatey:
        name: autodesk-fusion360
        state: present

    - name: Install gitkraken
      win_chocolatey:
        name: gitkraken
        state: present

    - name: Install notepadplusplus
      win_chocolatey:
        name: notepadplusplus
        state: latest

    - name: Install libreoffice-fresh
      win_chocolatey:
        name: libreoffice-fresh
        state: latest

    # - name: Install foxitreader
    #   win_chocolatey:
    #     name: foxitreader
    #     state: present

    # - name: Install firefox
    #   win_chocolatey:
    #     name: firefox
    #     state: latest

    # - name: Install googlechrome
    #   win_chocolatey:
    #     name: googlechrome
    #     state: latest
